services:
  postgres:
    image: ankane/pgvector:latest
    container_name: devbuddy-postgres

    environment:
      POSTGRES_DB: devbuddy
      POSTGRES_USER: devbuddy
      POSTGRES_PASSWORD: devbuddy_password

    ports:
      - "5432:5432"

    volumes:
      - devbuddy_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devbuddy -d devbuddy"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: devbuddy-api

    environment:
      POSTGRES_DB: devbuddy
      POSTGRES_USER: devbuddy
      POSTGRES_PASSWORD: devbuddy_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

    ports:
      - "8000:8000"
    
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  devbuddy_postgres_data: