services:
  postgres:
    image: ankane/pgvector:latest
    container_name: devbuddy-postgres

    environment:
      POSTGRES_DB: devbuddy
      POSTGRES_USER: devbuddy
      POSTGRES_PASSWORD: devbuddy_password

    ports:
      - "5432:5432"

    volumes:
      - devbuddy_postgres_data:/var/lib/postgresql/data

volumes:
  devbuddy_postgres_data: